---
abstract: 'Mason wrapper for Dancer'
author:
  - 'Yanick Champoux'
build_requires:
  Dancer::FileUtils: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101590'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Template-Mason
provides:
  Dancer::Template::Mason:
    file: lib/Dancer/Template/Mason.pm
    version: 0.002000
requires:
  Dancer: 0
  Dancer::Config: 0
  Dancer::Template::Abstract: 0
  FindBin: 0
  HTML::Mason: 0
  HTML::Mason::Interp: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dancer-Template-Mason
  homepage: http://search.cpan.org/dist/Dancer-Template-Mason/
  repository: git://github.com/yanick/Dancer-Template-Mason.git
version: 0.002000
